name: Build branch

on:
  push:
    branches:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}

permissions:
  id-token: write
  contents: read

jobs:

  build:
    name: Build
    uses: ./.github/workflows/build.yaml
    secrets: inherit